export const transactions = [
  { id: 1,   date: "01-01-2026", description: "January Salary",        category: "salary1",     type: "income", amount: 35000},
  { id: 2,   date: "12-02-2026", description: "uber ride",             category: "transport",   type: "expense", amount: 155},
  { id: 3,   date: "11-03-2026", description: "doctor checkup",        category: "health",      type: "expense", amount: 200},
  { id: 4,  date: "2026-01-15", description: "Electricity Bill",      category: "Utilities",   type: "expense", amount: 1200 },
  { id: 5,  date: "2026-01-20", description: "Amazon Purchase",       category: "Shopping",    type: "expense", amount: 2450 },
  { id: 6,  date: "2026-01-25", description: "Netflix Subscription",  category: "Entertainment", type: "expense", amount: 649 },
  { id: 7,  date: "2026-02-01", description: "Freelance Payment",     category: "Freelance",   type: "income",  amount: 12000 },
  { id: 8,  date: "2026-02-05", description: "February Salary",       category: "Salary",      type: "income",  amount: 45000 },
  { id: 9,  date: "2026-02-09", description: "Zomato Order",          category: "Food",        type: "expense", amount: 520 },
  { id: 10, date: "2026-02-14", description: "Ola Cab",               category: "Transport",   type: "expense", amount: 175 },
  { id: 11, date: "2026-02-18", description: "Gym Membership",        category: "Health",      type: "expense", amount: 1500 },
  { id: 12, date: "2026-02-22", description: "Flipkart Order",        category: "Shopping",    type: "expense", amount: 3200 },
  { id: 13, date: "2026-03-01", description: "March Salary",          category: "Salary",      type: "income",  amount: 45000 },
  { id: 14, date: "2026-03-06", description: "Dunzo Groceries",       category: "Food",        type: "expense", amount: 890 },
  { id: 15, date: "2026-03-10", description: "Metro Card Recharge",   category: "Transport",   type: "expense", amount: 500 },
  { id: 16, date: "2026-03-14", description: "Internet Bill",         category: "Utilities",   type: "expense", amount: 999 },
  { id: 17, date: "2026-03-19", description: "Movie Tickets",         category: "Entertainment", type: "expense", amount: 760 },
  { id: 18, date: "2026-03-24", description: "Freelance Project",     category: "Freelance",   type: "income",  amount: 8000 },
  { id: 19, date: "2026-03-28", description: "Doctor Visit",          category: "Health",      type: "expense", amount: 650 },
  { id: 20, date: "2026-04-01", description: "April Salary",          category: "Salary",      type: "income",  amount: 45000 },
  { id: 21, date: "2026-04-02", description: "Swiggy Order",          category: "Food",        type: "expense", amount: 440 },
  { id: 22, date: "2026-04-02", description: "Rapido Bike",           category: "Transport",   type: "expense", amount: 95 },
]
export const categories = ["All", "Salary", "Freelance", "Food", "Transport", "Utilities", "Shopping", "Entertainment", "Health"]